bootstrapper: "me.dueris.genesismc.Bootstrap"
loader: "me.dueris.genesismc.DependencyLoader"
load: POSTWORLD
name: "GenesisMC"
version: 'mc1.20-1.0.0'
main: "me.dueris.genesismc.GenesisMC"
api-version: "1.20"
authors: [ Dueris ]
folia-supported: false
description: "A port of the Origins mod to PaperMC servers with Custom Origins support"
website: "https://ko-fi.com/dueris"
dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: false
    Geyser-Spigot:
      load: AFTER
      required: false
    Floodgate:
      load: AFTER
      required: false
    SkinsRestorer:
      load: BEFORE
      required: false
