bootstrapper: "me.dueris.originspaper.Bootstrap"
loader: "me.dueris.originspaper.DependencyLoader"
load: POSTWORLD
name: "OriginsPaper"
version: 'mc1.21-1.0.4'
main: "me.dueris.originspaper.OriginsPaper"
api-version: "1.21"
authors: [ Dueris ]
folia-supported: false
description: "A port of the Origins mod to PaperMC servers with Custom Origins support"
website: "https://ko-fi.com/dueris"
dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: false
    Geyser-Spigot:
      load: AFTER
      required: false
    Floodgate:
      load: AFTER
      required: false
    SkinsRestorer:
      load: BEFORE
      required: false
