bootstrapper: "me.dueris.originspaper.Bootstrap"
loader: "me.dueris.originspaper.DependencyLoader"
load: POSTWORLD
name: "OriginsPaper"
version: "${fullVer}"
main: "me.dueris.originspaper.OriginsPaper"
api-version: "${apiVer}"
authors: [ Dueris ]
folia-supported: false
description: "A port of the Origins mod to PaperMC servers with Custom Origins support"
website: "https://ko-fi.com/dueris"
dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: false
    Geyser-Spigot:
      load: AFTER
      required: false
    Floodgate:
      load: AFTER
      required: false
    SkinsRestorer:
      load: BEFORE
      required: false

supportedVersions: ${supportedVersions}
default-language: "en_us"