bootstrapper: "io.github.dueris.originspaper.Bootstrap"
loader: "io.github.dueris.originspaper.DependencyLoader"
load: POSTWORLD
name: "OriginsPaper"
main: "io.github.dueris.originspaper.plugin.OriginsPlugin"
authors: [ Dueris ]
folia-supported: false
description: "A port of the Origins mod to PaperMC servers with Custom Origins support"
website: "https://ko-fi.com/dueris"
dependencies:
  server:
    SkinsRestorer:
      load: BEFORE
      required: false

supported: ${supported}
minecraft: ${mcVer}
plugin: ${pluginVer}
api-version: ${apiVer}
version: ${fullVer}
apoli: ${apoli}
default-language: "en_us"