load: POSTWORLD
name: Origins
authors: [ Dueris ]
description: "A full, but unofficial, port of Calio/Apoli/Origins to PaperMC servers"
website: "https://ko-fi.com/dueris"

dependencies:
  bootstrap:
    Eclipse:
      load: BEFORE
      required: false
      join-classpath: true

folia-supported: false
has-open-classloader: false

minecraft: ${minecraft}
plugin: ${version}
api-version: ${api}
version: ${full_version}
apoli: ${apoli}
calio: ${calio}
default-language: "en_us"

# eclipse config
wideners: [
  "origins.accesswidener",
  "calio.accesswidener",
  "fabricapi.accesswidener"
]

mixins: [
  "origins.mixins.json",
  "calio.mixins.json"
]

# mod entrypoints
datapack-entry: true
main: "io.github.dueris.originspaper.plugin.OriginsPlugin"
bootstrapper: "io.github.dueris.originspaper.Bootstrap"
loader: "io.github.dueris.originspaper.DependencyLoader"