bootstrapper: "io.github.dueris.originspaper.Bootstrap"
loader: "io.github.dueris.originspaper.DependencyLoader"
load: POSTWORLD
name: Origins
main: "io.github.dueris.originspaper.plugin.OriginsPlugin"
authors: [ Dueris ]

dependencies:
  bootstrap:
    Eclipse:
      load: BEFORE
      required: true
      join-classpath: true

folia-supported: false
has-open-classloader: false
description: "A full, but unofficial, port of Calio/Apoli/Origins to PaperMC servers"
website: "https://ko-fi.com/dueris"
supported: ${supported}
minecraft: ${mcVer}
plugin: ${pluginVer}
api-version: ${apiVer}
version: ${fullVer}
apoli: ${apoli}
calio: ${calio}
default-language: "en_us"

bootstrap:
  Eclipse:
    load: BEFORE
    required: true

wideners: [
  "origins.accesswidener",
  "calio.accesswidener",
  "fabricapi.accesswidener"
]

mixins: [
  "origins.mixins.json",
  "calio.mixins.json"
]